- name: Install uv python package management
  become: true
  become_user: "{{ real_user.stdout }}"
  shell: |
    pipx install uv
  environment:
    HOME: "{{ real_user_home.stdout }}"
    http_proxy: "{{ proxy | default('') }}"
    https_proxy: "{{ proxy | default('') }}"
  register: result

- name: Result
  debug:
    var: result
